MvcNetCoreExamen/Models/Comic.cs
namespace MvcNetCoreExamen.Models
{
    public class Comic
    {
        public int IdComic { get; set; }
        public string Nombre { get; set; }
        public string Imagen { get; set; }
        public string Descripcion { get; set; }
    }
}

MvcNetCoreExamen/Models/ErrorViewModel.cs
namespace MvcNetCoreExamen.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcNetCoreExamen/Controllers/ComicsController.cs
using Microsoft.AspNetCore.Mvc;
using MvcNetCoreExamen.Models;
using MvcNetCoreExamen.Repositories;

namespace MvcNetCoreExamen.Controllers
{
    public class ComicsController : Controller
    {
        private IRepositoryComics repo;

        public ComicsController(IRepositoryComics repo)
        {
            this.repo = repo;
        }

        public IActionResult Index()
        {
            List<Comic> comics = this.repo.GetComics();
            return View(comics);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Comic comic)
        {
            this.repo.InsertComic(comic.Nombre, comic.Imagen, comic.Descripcion);
            return RedirectToAction("Index");
        } 

        public IActionResult DeleteComic(int idcomic)
        {
            var comic = this.repo.GetComicID(idcomic);
            return View(comic);
            /*this.repo.DeleteComic(idcomic);
            return RedirectToAction("Index");*/
        }

        [HttpPost]
        public IActionResult DeleteComic(int idcomic, string nombre)
        {
            this.repo.DeleteComic(idcomic,nombre);
            return RedirectToAction("Index");
        }

        public IActionResult BuscadorComics()
        {
            ViewData["NOMBRES"] = this.repo.GetNombresComics();
            return View();
        }
        
        [HttpPost]
        public IActionResult BuscadorComics(string nombre)
        {
            ViewData["NOMBRES"] = this.repo.GetNombresComics();
            Comic comic = this.repo.GetComicNombre(nombre);
            return View(comic);
        }

        public IActionResult CreateProcedure()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateProcedure(string nombre, string imagen, string descripcion)
        {
            this.repo.InsertComicProcedure(nombre,imagen, descripcion);
            return RedirectToAction("Index");
        }
    }
}

MvcNetCoreExamen/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcNetCoreExamen.Models;
using System.Diagnostics;

namespace MvcNetCoreExamen.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcNetCoreExamen/Views/Comics/BuscadorComics.cshtml
@model Comic

@{
    List<string> nombres = ViewData["NOMBRES"] as List<string>;
}

<p>
    <a asp-controller="Comics" asp-action="Index">Ver Comics</a>
</p>

<h1>Buscador de empleados</h1>
<form method="post">
    <label>Seleccione un comic</label>
    <select name="nombre">
        @foreach (string nombre in nombres)
        {
            <option value="@nombre">@nombre</option>
        }
    </select>
    <button class="btn btn-outline-dark">
        Mostrar Comic
    </button>
</form>

@if(Model != null)
{
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Imagen</th>
                <th>Descripción</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><img src="@Model.Imagen" style="width: 200px; height: 200px;" /></td>
                <td>@Model.Descripcion</td>
            </tr>
        </tbody>
    </table>

}

MvcNetCoreExamen/Views/Comics/Create.cshtml
<h1>Nuevo Comic</h1>

<p>
    <a asp-controller="Comics" asp-action="Index">
        Volver atrás
    </a>
</p>

<form method="post">
    <label>Nombre</label>
    <input type="text" class="form-control" name="nombre"/>
    <label>Descripcion</label>
    <input type="text" class="form-control" name="descripcion" />
    <label>Imagen</label>
    <input type="text" class="form-control" name="imagen" />
    <br />
    <button class="btn btn-outline-primary">
        Crear Comic
    </button>
</form>

MvcNetCoreExamen/Views/Comics/CreateProcedure.cshtml
<h1> Crear Comic Procedure</h1>

<p>
    <a asp-action="Index" asp-controller="Comics">
        Volver Atras
    </a>
</p>

<form method="post">
    <label>Nombre</label>
    <input type="text" class="form-control" name="nombre" />
    <label>Descripcion</label>
    <input type="text" class="form-control" name="descripcion" />
    <label>Imagen</label>
    <input type="text" class="form-control" name="imagen" />
    <br />
    <button class="btn btn-outline-primary">
        Crear Comic
    </button>
</form>

MvcNetCoreExamen/Views/Comics/DeleteComic.cshtml
@model Comic

<h1>Eliminar comic</h1>

<p>
    <a asp-controller="Comics" asp-action="Index">Volver atrás</a>
</p>

<form method="post" asp-controller="Comics" asp-action="DeleteComic">
    <input type="hidden" name="idcomic" value="@Model.IdComic" />
    <input type="hidden" name="nombre" value="@Model.Nombre" />
    <label>Id comic</label>
    <input type="number" class="form-control" name="idComic" value="@Model.IdComic" disabled/>
    <label>Nombre</label>
    <input type="text" class="form-control" name="nombre" value="@Model.Nombre" disabled/>
    <br/>
    <button class="btn btn-outline-danger"> Borrar Comic </button>
</form>

MvcNetCoreExamen/Views/Comics/Index.cshtml
@model List<Comic>

<h1> Comics </h1>

<p>
    <a asp-controller="Comics" asp-action="Create">
        New Comic
    </a>
</p>
<p>
    <a asp-controller="Comics" asp-action="CreateProcedure">
        New Comic Procedure
    </a>
</p>


<table class="table table-bordered">
    <thead>
        <tr>
            <th>Id Comic</th>
            <th>Nombre</th>
            <th>Descripcion</th>
            <th>Imagen</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(Comic com in Model)
        {
            <tr>
                <td>@com.IdComic</td>
                <td>@com.Nombre</td>
                <td>@com.Descripcion</td>
                <td><img src="@com.Imagen" style="width: 200px; height:200px"/></td>
                <td>
                    <a asp-controller="Comics" asp-action="DeleteComic" asp-route-idComic="@com.IdComic" class="btn btn-close"></a>
                </td>
            </tr>
        }
    </tbody>
</table>

MvcNetCoreExamen/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcNetCoreExamen/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcNetCoreExamen</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcNetCoreExamen.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcNetCoreExamen</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Comics" asp-action="Index">
                                Comics
                            </a>
                        </li>
                        <li class="nav-item"> 
                            <a class="nav-link" asp-controller="Comics" asp-action="BuscadorComics">Buscador</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MvcNetCoreExamen - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>